### ISSUE TITLE
Setting Custom Variables 

### ISSUE THREAD

**Issue by alexkasemir** [BonifyByForteil/react-native-matomo#10]
Hey, great library so I was wondering if there were plans to add a function similar to [these](https://github.com/BonifyByForteil/react-native-piwik/blob/master/index.js) for setting user defined custom variables. I know that the iOS SDK uses the first three slots by default but I was wondering if there would an easy way to get access to them.

Thanks!

**Comment by diedsmiling** [comment]
Hi, at the moment we didn't plan to do anything like this, but a PR is always welcome :)

**Comment by forteil** [comment]
Hey, closing the issue as were no pull request. ;)
