### ISSUE TITLE
Matomo.org

### ISSUE THREAD

**Issue by Findus23** [BonifyByForteil/react-native-matomo#16]
Hi,

Many thanks for providing an integration for Piwik/Matomo. I have now added it to the list at https://matomo.org/integrate/

One thing: Would you mind renaming the SDK to the new brand name "Matomo"?

Thanks for making Matomo great!

**Comment by ChristopherStephan** [comment]
Hint: Piwik was renamed to Matomo (https://matomo.org/blog/2018/01/piwik-is-now-matomo/)

**Comment by diedsmiling** [comment]
Hi!
Thanks a lot for adding our project to the list of integrations, will take care next week to rename the package ;)
