### ISSUE TITLE
update native sdks

### ISSUE THREAD

**Issue by chrisgradl** [BonifyByForteil/react-native-matomo#17]
Hi do you plan to update the Android and iOS SDKs which are used to the latest version?

**Comment by diedsmiling** [comment]
Hi!
Thanks for asking. We do plan, but unfortunately can't provide any time estimations when it will be done. PR are always welcome though.

**Comment by alexsegura** [comment]
Looking at the [network](https://github.com/BonifyByForteil/react-native-matomo/network) section, you can see that there are some people that have forks that are more advanced than the main repo. 

@DajePepo has the most interesting fork. 
I don't know if lots of people are using this library, but it is listed on Matomo's website as the "official" React Native integration, so it would be cool if the library stays up-to-date. 
No offense here, huge thanks to people who have created & maintained this library until now 🙌

Maybe it would be a good idea to move it to [React Community](https://github.com/react-native-community)?

**Comment by DajePepo** [comment]
hey @alexsegura, we merged the fork you referred to.
Please update and let us know.
