### ISSUE TITLE
Module Piwik Requires main queue setup since it overrides init

### ISSUE THREAD

**Issue by mhaneef50673** [BonifyByForteil/react-native-matomo#19]
Team,

When using "react-native-piwik" in ios, we are hit with a warning message,

"Module Piwik requires main queue setup  since it overrides 'init' but doesnt implement 'requiresMainQueueSetup' 

And the app is crashing after doing Piwik initTracker

**Comment by DajePepo** [comment]
Hi, we can't reproduce the problem. Can you please give us more info?

**Comment by alexsegura** [comment]
It is quite easy to reproduce, just create a new projet with latest React Native, and launch the emulator.

<img width="419" alt="capture d ecran 2019-02-07 a 11 56 47" src="https://user-images.githubusercontent.com/1162230/52407057-83d6cc80-2acf-11e9-9f9b-f1ef3e60faa5.png">

**Comment by alexsegura** [comment]
Looking at the [network](https://github.com/BonifyByForteil/react-native-matomo/network) section, I found out @LorienHW has a fix for this. 

Check Outpatient/react-native-matomo@01906d837f9ae77530fc324b0a7bedfe6be8e2d4

**Comment by alexsegura** [comment]
I think this can be closed, the yellow box does not appear anymore since latest changes.

**Comment by alexsegura** [comment]
@DajePepo you can also close #21 🙂
