### ISSUE TITLE
Missing libBNFMatomo.a

### ISSUE THREAD

**Issue by jinchung** [BonifyByForteil/react-native-matomo#23]
When following the step on the README: Add libBNFMatomo.a (from Products under BNFMatomo.xcodeproj) to build target's Linked Frameworks and Libraries list

libBNFMatomo.a shows up in red in the navigator and my project fails to build with the following error:

```no such file or directory: '/Users/jin/Library/Developer/Xcode/DerivedData/BalanceWallet-ekprotsqsipsdcclhnvcvtvvzrbq/Build/Products/Release-iphoneos/libBNFMatomo.a'```

I was relying on the master branch and after a fresh yarn, picked up the latest changes to move from Piwik to Matomo.

**Comment by jinchung** [comment]
@DajePepo just wondering if you know anything about this - cheers

**Comment by DajePepo** [comment]
which dependency do you have in your package.json? Now you should point to react-native-matomo, react-native-piwik will be soon deprecated.

**Comment by jinchung** [comment]
Hey @DajePepo  - thanks!

So I've done the following:
- package.json is pointing to "react-native-matomo": "^0.1.1"
- I've followed the instructions under "Include the library" in the README (even though in Xcode, the "libBNFMatomo.a" is in red)
- I've removed the piwiktracker.xcdatamodeld file previously needed
- I've changed all instances of "Piwik" in my code to "Matomo"

Still getting this error when trying to build:
```no such file or directory: '/Users/jin/Library/Developer/Xcode/DerivedData/BalanceWallet-ekprotsqsipsdcclhnvcvtvvzrbq/Build/Products/Release-iphoneos/libBNFMatomo.a'```

**Comment by DajePepo** [comment]
Did you add libBNFMatomo.a to Target->Build Phases->Link Binary With Libraries?

**Comment by jinchung** [comment]
Yes as part of the instructions under "Include the library" in the README, I copied over the xcodeproject from node_modules and then dragged the "libBNFMatomo.a" from Products into my project's target's "Build Phases--> "Link Binary With Libraries"

**Comment by DajePepo** [comment]
umm... can you show me the entire log of the issue?

**Comment by mcarlson** [comment]
We are seeing this also when building through appcenter which uses xcodebuild. Here's a build log:
[1_Job.txt](https://github.com/BonifyByForteil/react-native-matomo/files/2885153/1_Job.txt)

**Comment by mcarlson** [comment]
I figured out how to fix this: I added BNFMatomo to the Target Dependencies section under the target's build phases tab... Seems like the documentation should be updated to add this step!

**Comment by alexsegura** [comment]
Same issue here, with `xcodebuild` on Travis.
As it is only happening in CI environment, it clearly related to the environment. 
I'm suspecting something related with Swift. 

You can see the raw log of a failed build [here](https://api.travis-ci.org/v3/job/498953774/log.txt).

**Comment by alexsegura** [comment]
It is also happening when archiving locally. 

I confirm @mcarlson workaround with adding to Target Dependencies works.
Is this normal?

**Comment by dejan9393** [comment]
I also have the same issue.
The solution provided by @mcarlson works for me too, however, this issue only seems to be occurring when I am archiving - running the app via the debug configuration seems to work fine.

**Comment by DajePepo** [comment]
We have just updated the readme according to the solution provided by @mcarlson. So we are going to close this issue.
