### ISSUE TITLE
Issue while debug build in android — Build fails!

### ISSUE THREAD

**Issue by introin** [BonifyByForteil/react-native-matomo#25]
I am getting build error with ./gradlew assembleDebug
I am using react native v 58 and on iOs to build this one. If i remove this package and its setting then it works. Tried reinstalling and followed all instruction to add in android project as well. Also cleared cache of grandle as well. Any soltuion will help me to use this library to my project. Thank you. 
Also[ tried this](https://forum.matomo.org/t/dexarchivebuilderexception-when-building-android-application-with-piwik-sdk/27518) but no luck.
`.FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/harshad/.gradle/caches/transforms-1/files-1.1/tracker-4.0.1.aar/0fcb52dc67200eb67552af6bce3655d4/jars/classes.jar

I have this in build.gradle:
     `buildscript {
     ext {
         buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'        
    }
}`

**Comment by alexsegura** [comment]
To make it work on Android, I had to make the following changes

coopcycle/coopcycle-app@8703c41390b4ed009f542e7da384017d723f0510

Does it help?

**Comment by introin** [comment]
Thank you @alexsegura I will check this out in few days, i carried forward with firebase analytics but there is no match to matomo so i will definitely use this one when i am free.

**Comment by aliazizi** [comment]
`Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.` is not actual error see error in stack our share full stacked exception

**Comment by lordkiz** [comment]
Consider enabling multiDex in `android/app/build.gradle` 's 
```
defaultConfig {
    ..........
    multiDexEnabled true
}
```
