### ISSUE TITLE
Maintenance status of the library

### ISSUE THREAD

**Issue by aeirola** [BonifyByForteil/react-native-matomo#27]
Hello, I started a integrating a React Native application with Matomo a couple months ago, and noticed at that time that this library was out of date, and not well maintained. Thus I opted to create a new library [`react-native-matomo-sdk`](https://github.com/terveystalo/react-native-matomo-sdk), which is still under development.

Although now it seems like this `react-native-matomo` library is again maintained, by apparently a new maintainer @DajePepo. Since there obviously isn't any point in having two competing libraries doing the same thing, I just wanted to check in to see what the plans for maintaining this library is.

**Comment by DajePepo** [comment]
Actually the library is maintained by the Bonify dev team which I am part of. We are trying to keep the library updated but we have limited resources so we hope that others can help. PRs are always welcome.

**Comment by aeirola** [comment]
Okay, nice to hear that the original team is still maintaining the library, and apparently backed by some financial organisation. Sounds like you would prefer to have more support from the community in keeping the library up to date, this sounds like a good idea, and I think the library could maybe be made a bit more approachable for outside developers by giving some more support on developing the library.

Part of the reason why we decided to spin up a separate library was that this library seemed hard to maintain and develop. There weren't really any clear process for how to start developing and testing the library. So instead of breaking something existing, we decided to build something new.

Some immediate ideas for making this library more maintainable for outside developers:

- Automated tests run on Travis / CircleCI or similar
- Instructions for how to set up a development environment and how to test changes locally
- Instructions on how to update the underlying iOS and android Matomo SDKs. This is probably one of the most common case for code changes.
- More concrete contribution guide

Of course setting this up, would require some effort from the maintainers, but in the long run it could produce more quality PRs from other developers, hopefully reducing the burden of the original maintainers.

If we can get a more vibrant developer community around this library, we would probably be happy to move over from our own library and pool our efforts into maintaining a single library.

**Comment by forteil** [comment]
Hey!
Thank you.
At the current stage of the company(Bonify) we have still pretty limited resources.
Even though your list makes sense, we have to balance between the bonify business critical developments and maintenance of this library.
We will consider your topics in our next developments, but unfortunately, it is hard to tell now about the timeline.
Thank yours very very much for your input!
