### ISSUE TITLE
Missing installation steps

### ISSUE THREAD

**Issue by alexsegura** [BonifyByForteil/react-native-matomo#29]
Hello, 

I had to do additional steps to have the library work. 

**Android**

1/ Allow Java 8 features as explained on [matomo-sdk-android](https://github.com/matomo-org/matomo-sdk-android/wiki/Troubleshooting)
2/ Add Timber in my `app/build.gradle` 
```
implementation "com.jakewharton.timber:timber:${rootProject.ext.timberVersion}"
```
3/ [Enable multidex](https://developer.android.com/studio/build/multidex), but this is certainly specific to my app

See coopcycle/coopcycle-app@8703c41390b4ed009f542e7da384017d723f0510

**iOS**

1/ Set up Swift and Objective-C Interoperability by creating an empty `*.swift` file. This is explained on [matomo-sdk-ios](https://github.com/matomo-org/matomo-sdk-ios/wiki/FAQ#how-to-use-the-matomotracker-from-objective-c)
2/ Bump Swift version used in XCode to `4.2`
3/ Add BNFMatomo to the Target Dependencies as explained by @mcarlson in #23  

See coopcycle/coopcycle-app@eade9389c98485ec6c9dda19d6723dc67e0f817b & coopcycle/coopcycle-app@f58561d4225591a2e126d73c53b0ad0bb8b89af0

**Comment by DajePepo** [comment]
> 1/ Set up Swift and Objective-C Interoperability by creating an empty `*.swift` file. This is explained on [matomo-sdk-ios](https://github.com/matomo-org/matomo-sdk-ios/wiki/FAQ#how-to-use-the-matomotracker-from-objective-c)

That's right. We didn't add it in readme because we thought it was out of scope in this project, but if you think it could be useful we can insert it.

> 2/ Bump Swift version used in XCode to `4.2`

Same

> 3/ Add BNFMatomo to the Target Dependencies as explained by @mcarlson in #23

Ok, if it fixes the problem we are going to mention it in the readme.

**Comment by alexsegura** [comment]
Ok thank you. I think it can definitely help people avoid troubles and searching for errors.
I can make a Pull Request to update the README 🙂 

Regarding

> 3/ Add BNFMatomo to the Target Dependencies as explained by @mcarlson in #23

Isn't it on your side? I don't know anything about Objective-C/XCode, but it is the only library I'm using that needs to do this. All libraries generally require things in `Link Binary With Libraries`. 

I noticed another library I'm using includes something in `Target Dependencies` itself. 

<img width="1347" alt="capture d ecran 2019-02-28 a 14 22 44" src="https://user-images.githubusercontent.com/1162230/53569522-b6bb3000-3b64-11e9-88fb-1ca787ef1c2d.png">
