### ISSUE TITLE
CustomDimension

### ISSUE THREAD

**Issue by irodeanu** [BonifyByForteil/react-native-matomo#31]
There is a chance to be implemented ?

**Comment by forteil** [comment]
Hey,
Can you provide us more info?
And if you think it could be useful, please propose a pull request.
Thanks a lot

**Comment by alexandrvicente** [comment]
Implemented on PR #33.

**Comment by omaiboroda** [comment]
Was merged in https://github.com/BonifyByForteil/react-native-matomo/pull/33
