### ISSUE TITLE
iOS archive build failing

### ISSUE THREAD

**Issue by mxmtsk** [BonifyByForteil/react-native-matomo#32]
I'm unable to archive my app through iOS. It fails with the following error:

```
ld: library not found for -lBNFMatomo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have followed the installation steps and when running the app via `react-native run-ios` it works fine.

**Comment by irodeanu** [comment]
Same issue

**Comment by DajePepo** [comment]
That was a known problem, we just updated the readme. Check it out.
