### ISSUE TITLE
Cannot read property 'initTracker' of undefined (iOS)

### ISSUE THREAD

**Issue by lutaev** [BonifyByForteil/react-native-matomo#36]
Hi there.

I'm new in react-native. I did all steps from installation guide, but got an error on iPhone 6:

![IMG_0009](https://user-images.githubusercontent.com/6015401/63222509-ab5ece00-c1b1-11e9-8945-3b9d166bb50b.jpg)

I started debugging and found that if I run something like:
```javascript
console.log(require('react-native').NativeModules)
``` 
in react-native-matomo/index.js, I see a list of modules in console, but there is no Matomo in this list.
I'm sure that I missed something, could you please help me? Should I run `react-native link`?

Thanks.

**Comment by alexandrvicente** [comment]
Have you followed the instructions at https://github.com/BonifyByForteil/react-native-matomo#ios?

**Comment by lordkiz** [comment]
Consider unlinking and then follow the installation instructions on the README
