### ISSUE TITLE
Compatibility with RN 0.60+ (?)

### ISSUE THREAD

**Issue by afiller** [BonifyByForteil/react-native-matomo#41]
In another thread I found the information that this repository is still maintained and my team and I are quite happy about this. Thank you!

Nevertheless, we have seen that a pull request from 2018 regarding autolinking (esp. cocoapods) is not merged yet and is also no longer working with the current version. Since the new RN versions now completely switched to this method, my question is if this change can be expected to be part of an upcoming update in the near future?

**Comment by akontaroudis** [comment]
For whoever runs into this, I managed to get Matomo working with react-native 0.61.5. This was quite painful and hacky, but personally don't know enough to fix it properly.

First of all I tried to manually link the package which didn't work at all. I upgraded from react-native 0.57, where it was working fine, so it was all there. I redid the linking a few times to ensure I'm not doing anything silly. Apologies but I haven't kept the log on what exactly was failing with the manual link.

Second attempt was to use the coldbess forked package with the podspec. That doesn't work either and it was throwing quite a few errors within react-native objc code itself. I have no clue why but with some search I fixed it by applying the attached patches. The patches automatically get applied in my build by "patch-package".

Adding it here for two reasons:
1) someone, as clueless as me, may find it useful
2) one of you bright people may have a better solution than patching react-native on install :)

[patches.zip](https://github.com/BonifyByForteil/react-native-matomo/files/4005856/patches.zip)

**Comment by lordkiz** [comment]
> For whoever runs into this, I managed to get Matomo working with react-native 0.61.5. This was quite painful and hacky, but personally don't know enough to fix it properly.
> 
> First of all I tried to manually link the package which didn't work at all. I upgraded from react-native 0.59.9, where it was working fine, so it was all there. I redid the linking a few times to ensure I'm not doing anything silly. Apologies but I haven't kept the log on what exactly was failing with the manual link.
> 
> Second attempt was to use the coldbess forked package with the podspec. That doesn't work either and it was throwing quite a few errors within react-native objc code itself. I have no clue why but with some search I fixed it by applying the attached patches. The patches automatically get applied in my build by "patch-package".
> 
> Adding it here for two reasons:
> 
> 1. someone, as clueless as me, may find it useful
> 2. one of you bright people may have a better solution than patching react-native on install :)
> 
> [patches.zip](https://github.com/BonifyByForteil/react-native-matomo/files/4005856/patches.zip)

I am working on this. For the time being, you can follow the installation process on the `Readme` and try my suggestions [here](https://github.com/BonifyByForteil/react-native-matomo/issues/47#issuecomment-594499058) if you are on > `RN0.61.x`
