### ISSUE TITLE
how to use customDimensions in react native

### ISSUE THREAD

**Issue by Abhi0059** [BonifyByForteil/react-native-matomo#44]
i want to use customDimensions in my react native app. i didn't found any tutorial or something related to this..please help me out with this.

**Comment by vinoth-am** [comment]
@Abhi0059 Updated library is not available in NPM. So you can try to point the libary to git repo.

 In package.json
"react-native-matomo": "^0.1.1"

Instead:
"react-native-matomo": "git+https://github.com/BonifyByForteil/react-native-matomo.git",
