### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by albat** [BonifyByForteil/react-native-matomo#49]
Hi,

The android part of this package doesn't support AndroidX
Since RN 0.60, AndroidX is supported.

Currently, when running the project in an AndroidX app, it fails because @NonNull is not defined and the package android.support.annotation.NonNull is not found

The fix is simple, just replace
`import android.support.annotation.NonNull;`
by
`import androidx.annotation.NonNull;`

It will be a breaking change for non AndroidX app but it's necessary

**Comment by hannahcx** [comment]
Also having this issue...

**Comment by gabrielmoncea** [comment]
I detailed how I manage to integrate matomo in #60

**Comment by lordkiz** [comment]
Fixed in 0.2.0
