### ISSUE TITLE
Link the latest podspec manually to project

### ISSUE THREAD

**Issue by krakzk** [BonifyByForteil/react-native-matomo#56]
As the latest 0.1.2 is not published into repository, is there any way to link it to a project? I have tried manually linking it, but shows unable to find podspec.

RN : 0.62.2

**Comment by krakzk** [comment]
PLease ignore

**Comment by kenobi91** [comment]
@krakzk can you tell me how you resolved this issue ?

**Comment by krakzk** [comment]
@kenobi91 You can follow the steps given in  readme and add the podspec manually. There might be build errors, where you may need to edit the search header paths in the pods from xcode.
