### ISSUE TITLE
React/RCTAssert.h file not found

### ISSUE THREAD

**Issue by krakzk** [BonifyByForteil/react-native-matomo#57]
Tried updating my RN to 0.62.2 and using the podspec command in README linked it to my project. But once trying to run the app, getting error
'React/RCTAssert.h file not found'
Tried various methods to link, clean the project. But none worked. 
If i remove the import in RCTLog.h , it shows other dependencies are not found, so he base reason is the plugin.
Any idea on resolving this issue?

**Comment by vinoth-am** [comment]
Check this issue [47](https://github.com/BonifyByForteil/react-native-matomo/issues/47) it might help.

**Comment by lordkiz** [comment]
@krakzk does 0.2.0 solve the issue for you?
