### ISSUE TITLE
opt-out RTCLog

### ISSUE THREAD

**Issue by chunghe** [BonifyByForteil/react-native-matomo#9]
Thank you for this great lib!
I have one question though. Is there any way to opt-out the message print to console.log? It creates noise while debugging. It would be great to have an option to opt-in/out so we could focus on the debug messages we're developing.

![2017-10-16 12 52 28](https://user-images.githubusercontent.com/78242/31595844-f3e64dd4-b203-11e7-97bd-7a2d9c40c46e.png)

**Comment by diedsmiling** [comment]
Hi!
Thanks for the interest in our project. Yes, I think we can improve that. Right now logs are shown just for IOS version.

**Comment by forteil** [comment]
Hey!
Thanks for your input. We are currently focusing on new business features for bonify and has limited resources for maintenance of this lib. However, please feel free to open the pull requests. 
Thanks
